spring:
  profiles:
    active: dev
server:
  address: localhost
  port: 8081
  servlet:
    context-path: '/api'
  ssl:
    key-password: 'zaq12wsx'
    key-store: 'src/main/resources/keystore.jks'
    key-store-password: 'zaq12wsx'