spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: paka
    password: paka

  profiles:
    active: dev
server:
  address: localhost
  port: 8081
  servlet:
    context-path: '/api'
services:
  notificationQueue: notifications
  rest:
    urls:
      pakaWarehouseApiUrl: 'http://localhost:8082/api'
      pakaUsersApiUrl: 'http://localhost:5000/api'