spring:
  h2:
    console:
      path: '/h2'
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: springuser
    password: springsecret
    initialization-mode: always
  jpa:
    show-sql: true
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
        SQL: DEBUG