spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  jpa:
    defer-datasource-initialization: true

  profiles:
    active: prod
server:
  address: localhost
  port: 8081
  servlet:
    context-path: '/api'
services:
  security:
    jwtSecret: 'rRYaQlIsv4TiaBuqVlCurRYaQlIsv4TiaBuqVlCu'
    audience: 'Test'
    issuer: 'Test'
  notificationQueue: januszex
  rest:
    urls:
      pakaWarehouseApiUrl: 'http://localhost:8083/api'
      pakaUsersApiUrl: 'http://localhost:5000/api'
