INSERT INTO PARCEL_TYPES (ID, IS_ACTIVE, DESCRIPTION, NAME, PRICE)
VALUES (1, true, 'testowy typ', 'test', 21.37);
INSERT INTO PARCEL_TYPES (ID, IS_ACTIVE, DESCRIPTION, NAME, PRICE)
VALUES (2, true, 'small', 'small', 9.99);
INSERT INTO PARCEL_TYPES (ID, IS_ACTIVE, DESCRIPTION, NAME, PRICE)
VALUES (3, true, 'medium', 'medium', 14.99);
INSERT INTO PARCEL_TYPES (ID, IS_ACTIVE, DESCRIPTION, NAME, PRICE)
VALUES (4, true, 'large', 'large', 24.99);
INSERT INTO ADDRESS (ID, BUILDING_NUMBER, CITY, FLAT_NUMBER, POSTAL_CODE, STREET)
VALUES (1, 'string', 'string', 'string', '21-370', 'string');
INSERT INTO ADDRESS (ID, BUILDING_NUMBER, CITY, FLAT_NUMBER, POSTAL_CODE, STREET)
VALUES (2, 'string', 'string', 'string', '21-370', 'string');
INSERT INTO PARCEL (ID, IS_DATE_MOVED, EXPECTED_COURIER_ARRIVAL_DATE, IS_FEE_PAID, IS_MARKED_TO_RETURN, IS_PAID,
                    PARCEL_FEE, PARCEL_PRICE, PIN, RECEIVER_DETAILS, RECEIVER_EMAIL_ADDRESS, RECEIVER_PHONE_NUMBER,
                    SENDER_DETAILS, SENDER_EMAIL_ADDRESS, SENDER_PHONE_NUMBER, SENDING_USER_ID, DELIVERY_ADDRESS_ID,
                    PARCEL_TYPE_ID, SENDER_ADDRESS_ID)
VALUES (1, false, '2021-12-05', false, false, false, 21.37, 10.00, '8279', 'string', 'string@s.pl', 'string', 'string',
        'string@s.pl', 'string', '9b7c519f-40a9-4707-99ea-b645a75aa4a2', 1, 1, 2);
INSERT INTO PARCEL_OBSERVER_IDS (PARCEL_ID, OBSERVER_IDS)
VALUES (1, '9b7c519f-40a9-4707-99ea-b645a75aa4a2');
INSERT INTO PARCEL_STATE (DTYPE, ID, CHANGE_TIME, CURRENT, COURIER_ID, WAREHOUSE_ID, WAREHOUSE_TYPE, PARCEL_ID,
                          PREVIOUS_STATE_ID)
VALUES ('AtSender', 99999, '2021-12-05 12:28:02.936048', true, null, 1, 0, 1, null);
