create table ADDRESS
(
	ID BIGSERIAL
		primary key,
	BUILDING_NUMBER TEXT not null,
	CITY TEXT not null,
	FLAT_NUMBER TEXT,
	POSTAL_CODE TEXT not null,
	STREET TEXT not null
);

create table PARCEL_TYPES
(
	ID BIGSERIAL
		primary key,
	IS_ACTIVE BOOLEAN not null,
	DESCRIPTION TEXT not null,
	NAME TEXT not null,
	PRICE DECIMAL(19,2) not null
);

create table PARCEL
(
	ID BIGSERIAL
		primary key,
	IS_DATE_MOVED BOOLEAN not null,
	EXPECTED_COURIER_ARRIVAL_DATE DATE,
	IS_FEE_PAID BOOLEAN not null,
	IS_MARKED_TO_RETURN BOOLEAN not null,
	IS_PAID BOOLEAN not null,
	PARCEL_FEE DECIMAL(19,2) not null,
	PARCEL_PRICE DECIMAL(19,2) not null,
	PIN VARCHAR(4) not null,
	RECEIVER_DETAILS TEXT not null,
	RECEIVER_EMAIL_ADDRESS TEXT,
	RECEIVER_PHONE_NUMBER TEXT,
	SENDER_DETAILS TEXT not null,
	SENDER_EMAIL_ADDRESS TEXT not null,
	SENDER_PHONE_NUMBER TEXT not null,
	SENDING_USER_ID VARCHAR(255) not null,
	DELIVERY_ADDRESS_ID BIGINT not null
		constraint UK_N9LSXLKBKADRQUWOFJV7UE7D4
			unique,
	PARCEL_TYPE_ID BIGINT not null,
	SENDER_ADDRESS_ID BIGINT not null
		constraint UK_BS4J9SPCISDQ2FWWK16364Y8H
			unique,
	constraint FK995BED6YLDDVHFM97CGMBVK5Q
		foreign key (PARCEL_TYPE_ID) references PARCEL_TYPES (ID),
	constraint FKEB3NN2CXUXHOSB6G4G7FYO7T8
		foreign key (DELIVERY_ADDRESS_ID) references ADDRESS (ID),
	constraint FKIA4MCP57FWQFOK46FIVKNVSOW
		foreign key (SENDER_ADDRESS_ID) references ADDRESS (ID)
);

create table DELIVERY_ATTEMPT
(
	ID BIGSERIAL
		primary key,
	COURIER_ID VARCHAR(255) not null,
	DATE_TIME TIMESTAMP not null,
	PARCEL_ID BIGINT not null,
	constraint FK2AAVNXWFIDJBIFPT0A4TTAY43
		foreign key (PARCEL_ID) references PARCEL (ID)
);

create table PARCEL_OBSERVER_IDS
(
	PARCEL_ID BIGINT not null,
	OBSERVER_IDS VARCHAR(255),
	constraint FKCD1TGXVCNF82XGFQ38TB6S5X3
		foreign key (PARCEL_ID) references PARCEL (ID)
);

create table PARCEL_STATE
(
	DTYPE VARCHAR(31) not null,
	ID BIGSERIAL
		primary key,
	CHANGE_TIME TIMESTAMP not null,
	CURRENT BOOLEAN not null,
	COURIER_ID VARCHAR(255),
	WAREHOUSE_ID BIGINT,
	WAREHOUSE_TYPE INTEGER,
	PARCEL_ID BIGINT not null,
	PREVIOUS_STATE_ID BIGINT,
	constraint FKQIS654WVBCBAOU94N4W7P4EC3
		foreign key (PREVIOUS_STATE_ID) references PARCEL_STATE (ID),
	constraint FKRBF9T5AB5D5H5MNBJ6RFNGF8T
		foreign key (PARCEL_ID) references PARCEL (ID)
);

